"""stable PKs + external codes

Revision ID: c391d4ad47bf
Revises: 
Create Date: 2025-09-01 10:18:19.284482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c391d4ad47bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_stations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('weather_station_code', sa.String(), nullable=False),
    sa.Column('weather_station_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_station_code')
    )
    op.create_table('hydropower_plants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hpp_code', sa.String(), nullable=False),
    sa.Column('hpp_name', sa.Text(), nullable=False),
    sa.Column('weather_station_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['weather_station_id'], ['weather_stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hpp_code')
    )
    op.create_table('rainfall_6min',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.CheckConstraint("MOD((EXTRACT(EPOCH FROM ts_utc))::int, 360) = 0", name="chk_6min_aligned"),
    sa.CheckConstraint('rainfall_mm >= 0', name='chk_rain_nonneg'),
    sa.ForeignKeyConstraint(['station_id'], ['weather_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'ts_utc', name='uniq_station_ts')
    )
    op.create_index('idx_rain_station_ts', 'rainfall_6min', ['station_id', 'ts_utc'], unique=False)
    op.create_index('idx_rain_ts', 'rainfall_6min', ['ts_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rain_ts', table_name='rainfall_6min')
    op.drop_index('idx_rain_station_ts', table_name='rainfall_6min')
    op.drop_table('rainfall_6min')
    op.drop_table('hydropower_plants')
    op.drop_table('weather_stations')
    # ### end Alembic commands ###
